apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promethues-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - prometheus.thinkeod.com
    secretName: p-tls
  rules:
  - host: prometheus.thinkeod.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: p-svc   ######
            port:
              number: 80  ####


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - ingress-nginx.thinkeod.com
    secretName: goose-tls
  rules:
  - host: ingress-nginx.thinkeod.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: goose-svc   ######
            port:
              number: 80  ####


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - argocd.thinkeod.com
    secretName: aa-tls
  rules:
  - host: argocd.thinkeod.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: aa-svc   ######
            port:
              number: 80  ####