variable "ami" {}
variable "jenkins-SG" {}
variable "key_name" {}
variable "private-subnet" {}
variable "agent_ip" {}
variable "kubeconfig" {}
variable "access-key" {}   
variable "secret-key" {}  
variable "regions" {}  
variable "cluster_name" {}  